stages:
  - test
  - build

before_script:
  - dart pub get

test:
  image: dart:stable-sdk
  stage: test
  script:
    - dart test
  tags:
    - docker
  
build-linux:
  image: dart:stable-sdk
  stage: build
  script:
    - dart compile exe bin/aoc2015.dart -o aoc2015-linux-x64 --target-os linux
  artifacts:
    paths:
      - aoc2015-linux-x64
  tags:
    - docker
  only:
    - /^feature/.*$/
    - main

build-macos:
  stage: build
  script:
    - dart compile exe bin/aoc2015.dart -o aoc2015-darwin-x64 --target-os macos
  artifacts:
    paths:
      - aoc2015-darwin-x64
  tags:
    - macos
  only:
    - /^feature/.*$/
    - main

build-windows:
  stage: build
  script:
    - dart compile exe bin/aoc2015.dart -o aoc2015-windows-x64.exe --target-os windows
  artifacts:
    paths:
      - aoc2015-windows-x64.exe
  tags:
    - windows
  only:
    - /^feature/.*$/
    - main
