image: dart:stable-sdk

stages:
  - test
  - build

before_script:
  - dart pub get

test:
  stage: test

  script:
    - dart test

  tags:
    - docker
  
build:
  stage: build

  script:
    - dart compile exe bin/aoc2015.dart -o bin/aoc2015-darwin-x64 --target-os macos
    - dart compile exe bin/aoc2015.dart -o bin/aoc2015-linux-x64 --target-os linux
    - dart compile exe bin/aoc2015.dart -o bin/aoc2015-windows-x64.exe --target-os windows

  artifacts:
    paths:
      - bin/aoc2015-darwin-x64
      - bin/aoc2015-linux-x64
      - bin/aoc2015-windows-x64.exe
  
  tags:
    - docker
  
  only:
    - /^feature/.*$/
    - main
