image: dart:stable-sdk

stages:
  - test_coverage

before_script:
  - dart pub get

test_coverage:
  stage: test_coverage

  script:
    - apt-get update -qq && apt-get install -y -qq lcov
    - dart test --coverage ./lib 
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  
  artifacts:
    paths:
      - coverage
  tags:
    - docker

  only:
    - /^feature/.*$/
    - merge_requests
    #- main
