image: cirrusci/flutter:stable

stages:
  - test_coverage

before_script:
  - dart pub get
  - dart clean
  - dart --version

test_coverage:
  stage: test_coverage

  script:
    - dart test --coverage ./lib 
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  
  artifacts:
    paths:
      - coverage
  tags:
    - docker

  only:
    - /^feature/.*$/
    - merge_requests
    #- main
